openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
  description: API endpoints for user authentication

components:
  securitySchemes:
    bearerAuth:
      description: "#### Example: Bearer [TOKEN]"
      type: http
      scheme: bearer
      bearerFormat: JWT

# ----------->> AUTH <<----------

# -----> AUTH.REGISTER <<-----
paths:
  /api/v1/auth/signup:
    post:
      summary: Register a new user
      security:
        - bearerAuth: []
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: example@email.com
                password:
                  type: string
                  example: password123
                role:
                  type: string
                  example: student
                otp:
                  type: string
                  example: abcd1234
      responses:
        201:
          description: User has been created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: "User authenticated successfully"
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                        example: "67c09b67191a749b67191a74"
                      email:
                        type: string
                        example: "example@mail.com"
                      password:
                        type: string
                        example: "password123"
                      role:
                        type: string
                        example: "student"
                      status:
                        type: string
                        example: "none"
                      createdAt:
                        type: string
                        example: "2025-02-27T17:05:43.338Z"
                      updatedAt:
                        type: string
                        example: "2025-02-27T17:05:43.338Z"
                      userId:
                        type: string
                        example: "10"

  # -----> AUTH.LOGIN <<-----
  /api/v1/auth/login:
    post:
      summary: Log in an existing user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: "User authenticated successfully"
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                        example: "67c09b67191a749b67191a74"
                      email:
                        type: string
                        example: "example@mail.com"
                      password:
                        type: string
                        example: "password123"
                      role:
                        type: string
                        example: "student"
                      status:
                        type: string
                        example: "none"
                      createdAt:
                        type: string
                        example: "2025-02-27T17:05:43.338Z"
                      updatedAt:
                        type: string
                        example: "2025-02-27T17:05:43.338Z"
                      userId:
                        type: string
                        example: "10"
                      token:
                        type: string
                        example: "jwt_token"

  # -----> AUTH.SEND_OTP <<-----
  /api/v1/auth/sendOtp:
    post:
      summary: Send verification OTP email to user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "user@example.com"
      responses:
        200:
          description: OTP sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "OTP sent successfully."

  # ----------->> USER <<----------
  # -----> USER.GET <<-----
  /api/v1/user/:
    get:
      summary: Get all users
      security:
        - bearerAuth: []
      tags:
        - User
      responses:
        200:
          description: User has been Fetched successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: "User has been Fetched successfully."
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          example: "67a8cd4f4a3c34a3c34a3c38"
                        email:
                          type: string
                          example: "example@email.com"
                        role:
                          type: string
                          example: "admin"
                        status:
                          type: string
                          example: "none"
                        createdAt:
                          type: string
                          example: "2025-02-09T15:44:15.437Z"
                        updatedAt:
                          type: string
                          example: "2025-02-09T15:44:15.437Z"
                        userId:
                          type: integer
                          example: 1

  # -----> USER.GET BY ID<<-----
  /api/v1/user/{userId}:
    get:
      summary: Get User by userId
      security:
        - bearerAuth: []
      tags:
        - User
      responses:
        200:
          description: User has been Fetched successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: "User has been Fetched successfully."
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                        example: "67a8cd4f4a3c34a3c34a3c38"
                      email:
                        type: string
                        example: "example@email.com"
                      role:
                        type: string
                        example: "admin"
                      status:
                        type: string
                        example: "none"
                      createdAt:
                        type: string
                        example: "2025-02-09T15:44:15.437Z"
                      updatedAt:
                        type: string
                        example: "2025-02-09T15:44:15.437Z"
                      userId:
                        type: integer
                        example: 1
    put:
      summary: Update User by userId
      security:
        - bearerAuth: []
      tags:
        - User
      requestBody:
        description: Update user details.
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "kasish@academia.edu"
                role:
                  type: string
                  example: "teacher"
                status:
                  type: string
                  example: "none"
              required:
                - email
                - role
                - status
      responses:
        200:
          description: User has been Updated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: "User has been Updated successfully."
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                        example: "67a8cd4f4a3c34a3c34a3c38"
                      email:
                        type: string
                        example: "example@email.com"
                      role:
                        type: string
                        example: "admin"
                      status:
                        type: string
                        example: "none"
                      createdAt:
                        type: string
                        example: "2025-02-09T15:44:15.437Z"
                      updatedAt:
                        type: string
                        example: "2025-02-09T15:44:15.437Z"
                      userId:
                        type: integer
                        example: 1
