export const ROUTES = {
  BASE: "/api/v1",
  ALL: "*",
  DOCS: "/api/docs",
  AUTH: {
    BASE: "/auth",
    LOGIN: "/login",
    SIGNUP: "/signup",
    SEND_OTP: "/sendOtp",
  },
  USER: {
    BASE: "/user",
    GET: "/",
    GET_BY_ID: "/:userId",
    UPDATE: "/:userId",
    DELETE: "/:userId",
  },
  UPDATE: {
    BASE: "/update",
    GET: "/",
    CREATE: "/",
    GET_BY_ID: "/:updateId",
    UPDATE: "/:updateId",
    DELETE: "/:updateId",
  },
  INSTITUTE: {
    BASE: "/institute",
    GET: "/",
    CREATE: "/",
    GET_BY_ID: "/:instituteId",
    UPDATE: "/:instituteId",
    DELETE: "/:instituteId",
  },
  SUBJECT: {
    BASE: "/subject",
    GET: "/",
    CREATE: "/",
    GET_BY_ID: "/:subjectId",
    UPDATE: "/:subjectId",
    DELETE: "/:subjectId",
  },
  ATTENDANCE: {
    BASE: "/attendance",
    GET: "/",
    GET_BY_ID: "/:attendanceId",
    ADD_RECORD: "/:attendanceId/add",
    CREATE: "/",
    UPDATE: "/:attendanceId",
    DELETE: "/:attendanceId",
  },
  PROFILE: {
    BASE: "/profile",
    GET: "/",
    CREATE: "/",
    GET_BY_ID: "/:profileId",
    UPDATE: "/:profileId",
    DELETE: "/:profileId",
  },
  FEES: {
    BASE: "/fees",
    GET: "/",
    CREATE: "/",
    GET_BY_ID: "/:feeId",
    UPDATE: "/:feeId",
    DELETE: "/:feeId",
  },
  HALLTICKET: {
    BASE: "/halltickets",
    GET: "/",
    CREATE: "/",
    GET_BY_ID: "/:hallticketId",
    UPDATE: "/:hallticketId",
    DELETE: "/:hallticketId",
  },
  CLASS: {
    BASE: "/class",
    GET: "/",
    GET_BY_ID: "/:classId",
    CREATE: "/",
    UPDATE: "/:classId",
    DELETE: "/:classId",
  },
  TIMETABLE: {
    BASE: "/timetable",
    GET: "/",
    GET_BY_ID: "/:timetableId",
    CREATE: "/",
    UPDATE: "/:timetableId",
    DELETE: "/:timetableId",
  },
};
